---
- name: include packages variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'        # RedHat-7
      paths: '../vars'
  become: true

- name: install requirement packages
  dnf:
    name: '{{ packages }}'
    state: present
  become: true